# Generated by Django 5.0.2 on 2024-04-07 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('33f504d4-acde-46d6-b66f-d1b6a63ea804'), editable=False, primary_key=True, serialize=False),
        ),
    ]
